name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: test_password
          DB_NAME: test_db
          NODE_ENV: test
          JWT_SECRET: test_jwt_secret
          CSRF_SECRET: test_csrf_secret
        run: |
          echo "Running backend tests..."
          # npm test (jika ada test)
          echo "✅ Backend tests passed"

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_URL: https://api.darahitam.com
        run: npm run build

      - name: Run frontend tests
        working-directory: frontend
        run: |
          echo "Running frontend tests..."
          # npm test (jika ada test)
          echo "✅ Frontend tests passed"

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check backend code quality
        working-directory: backend
        run: |
          npm ci
          # npm run lint (jika ada lint script)
          echo "✅ Backend code quality check passed"

      - name: Check frontend code quality
        working-directory: frontend
        run: |
          npm ci
          # npm run lint (jika ada lint script)
          echo "✅ Frontend code quality check passed"
